# Generated by Django 5.0.6 on 2025-11-27 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diocesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(default='Ecuador', max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sacramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('orden', models.PositiveSmallIntegerField()),
                ('iniciacion', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
                ('diocesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parroquias', to='sacramentos.diocesis')),
            ],
        ),
        migrations.CreateModel(
            name='Sacerdote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('parroquia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sacerdotes', to='sacramentos.parroquia')),
            ],
        ),
        migrations.CreateModel(
            name='Celebracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_celebracion', models.DateField()),
                ('notas', models.TextField(blank=True)),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sacramentos.parroquia')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sacramentos.persona')),
                ('sacerdote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sacramentos.sacerdote')),
                ('sacramento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sacramentos.sacramento')),
            ],
        ),
    ]
